"""Aggregation over request_audit for the dashboard.

Everything here is a sum, a count or a percentile over rows that were
written by real requests. Nothing is invented: a window with no rows
reports zeros and null percentiles, not placeholders. Every estimated
figure (cost, energy, CO2) carries the `basis` string from its config.

Percentiles are computed in Python over the window's values. SQLite has no
percentile function, and at hackathon scale a window is thousands of rows,
not millions; the query is capped so a runaway window cannot exhaust
memory.
"""

from __future__ import annotations

import json
import math
from collections import Counter
from datetime import datetime, timedelta, timezone

from sqlalchemy import func, select

from app.audit.database import session_scope
from app.audit.estimates import get_pricing, get_sustainability
from app.audit.models import RequestAudit, ReviewRequest
from app.contracts.audit import AuditReport, AuditReportSection
from app.contracts.metrics import (
    CostStats,
    LatencyStats,
    MetricsResponse,
    ProviderMetricsResponse,
    ProviderStat,
    RuleCount,
    SecurityMetricsResponse,
    SustainabilityMetricsResponse,
    TokenStats,
)

_MAX_ROWS = 50_000

DISCLAIMER = (
    "This report is transaction evidence generated by Aegis. It supports a "
    "deployer's own record-keeping and oversight processes. It is not a "
    "conformity assessment and does not itself establish legal compliance. "
    "Cost, energy and carbon figures are estimates whose assumptions are stated "
    "in config/pricing.yaml and config/sustainability.yaml."
)


def _since(window_hours: int) -> datetime:
    return datetime.now(timezone.utc) - timedelta(hours=window_hours)


def _rows(tenant_id: str, window_hours: int) -> list[RequestAudit]:
    with session_scope() as s:
        rows = s.execute(
            select(RequestAudit)
            .where(RequestAudit.tenant_id == tenant_id, RequestAudit.timestamp >= _since(window_hours))
            .order_by(RequestAudit.timestamp.desc())
            .limit(_MAX_ROWS)
        ).scalars().all()
        s.expunge_all()
        return list(rows)


def percentile(values: list[float], p: float) -> float | None:
    """Nearest-rank percentile. None when there is nothing to rank."""
    if not values:
        return None
    ordered = sorted(values)
    rank = math.ceil(p / 100.0 * len(ordered))  # 1-based nearest rank
    k = max(0, min(len(ordered) - 1, rank - 1))
    return round(ordered[k], 3)


def _mean(values: list[float]) -> float | None:
    return round(sum(values) / len(values), 3) if values else None


# ---------------------------------------------------------------------------
# GET /api/metrics
# ---------------------------------------------------------------------------


def overview(tenant_id: str = "default", window_hours: int = 24) -> MetricsResponse:
    rows = _rows(tenant_id, window_hours)
    pricing = get_pricing()

    total = [r.latency_total_ms for r in rows if r.latency_total_ms is not None]
    inspect = [r.latency_inspect_ms for r in rows if r.latency_inspect_ms is not None]

    spend = sum(r.estimated_cost_usd or 0.0 for r in rows)
    saved = sum(r.estimated_savings_usd or 0.0 for r in rows)

    return MetricsResponse(
        window_hours=window_hours,
        total_requests=len(rows),
        blocked_requests=sum(1 for r in rows if r.policy_action == "BLOCK"),
        sanitized_requests=sum(1 for r in rows if r.policy_action == "SANITIZE"),
        latency=LatencyStats(
            p50_ms=percentile(total, 50),
            p95_ms=percentile(total, 95),
            p99_ms=percentile(total, 99),
            mean_ms=_mean(total),
            inspector_overhead_p50_ms=percentile(inspect, 50),
            inspector_overhead_p95_ms=percentile(inspect, 95),
        ),
        tokens=TokenStats(
            input_tokens=sum(r.input_tokens or 0 for r in rows),
            output_tokens=sum(r.output_tokens or 0 for r in rows),
            total_tokens=sum(r.total_tokens or 0 for r in rows),
        ),
        cost=CostStats(
            estimated_spend_usd=round(spend, 6),
            estimated_saved_usd=round(saved, 6),
            basis=(
                f"{pricing.basis} Savings are counted against "
                f"{pricing.savings_counterfactual_model} on cache hits."
            ),
        ),
    )


# ---------------------------------------------------------------------------
# GET /api/metrics/security
# ---------------------------------------------------------------------------


def security(tenant_id: str = "default", window_hours: int = 24) -> SecurityMetricsResponse:
    rows = _rows(tenant_id, window_hours)
    rule_counter: Counter[str] = Counter()
    for r in rows:
        for rule in r.rules_fired or []:
            rule_counter[rule] += 1

    with session_scope() as s:
        since = _since(window_hours)
        by_status = dict(
            s.execute(
                select(ReviewRequest.status, func.count())
                .where(ReviewRequest.tenant_id == tenant_id, ReviewRequest.created_at >= since)
                .group_by(ReviewRequest.status)
            ).all()
        )

    return SecurityMetricsResponse(
        window_hours=window_hours,
        pii_detections=sum(r.pii_count for r in rows),
        secret_detections=sum(r.secret_count for r in rows),
        injection_blocks=sum(1 for r in rows if r.block_code == "PROMPT_INJECTION_BLOCKED"),
        credential_blocks=sum(1 for r in rows if r.block_code == "CREDENTIAL_LEAK_PREVENTED"),
        egress_flags=sum(1 for r in rows if r.egress_flagged),
        reviews_pending=int(by_status.get("PENDING", 0)),
        reviews_approved=int(by_status.get("APPROVED", 0)),
        reviews_denied=int(by_status.get("DENIED", 0)),
        top_rules=[RuleCount(rule_id=k, count=v) for k, v in rule_counter.most_common(10)],
    )


# ---------------------------------------------------------------------------
# GET /api/metrics/sustainability
# ---------------------------------------------------------------------------


def sustainability(tenant_id: str = "default", window_hours: int = 24) -> SustainabilityMetricsResponse:
    rows = _rows(tenant_id, window_hours)
    sus = get_sustainability()

    hits = [r for r in rows if r.cache_hit]
    misses = [r for r in rows if not r.cache_hit and r.provider]
    energy = sum(r.estimated_energy_wh or 0.0 for r in rows)
    co2 = sum(r.estimated_co2_g or 0.0 for r in rows)

    # Avoided on cache hits: the mean tokens of provider-served requests in
    # the window, priced at the counterfactual model's class. If nothing was
    # provider-served, we have no counterfactual and report zero avoided.
    served_tokens = [r.total_tokens for r in misses if r.total_tokens]
    avoided_wh = 0.0
    if hits and served_tokens:
        mean_tokens = sum(served_tokens) / len(served_tokens)
        avoided_wh = sus.energy_wh(sus.avoided_counterfactual_model, int(mean_tokens)) * len(hits)
    avoided_co2 = sus.co2_g(avoided_wh)

    considered = len(hits) + len(misses)
    return SustainabilityMetricsResponse(
        window_hours=window_hours,
        cache_hit_rate=round(len(hits) / considered, 4) if considered else 0.0,
        cache_hits=len(hits),
        cache_misses=len(misses),
        estimated_energy_wh=round(energy, 4),
        estimated_co2_g=round(co2, 4),
        estimated_energy_avoided_wh=round(avoided_wh, 4),
        estimated_co2_avoided_g=round(avoided_co2, 4),
        basis=(
            f"{sus.basis} Avoided figures assume each cache hit replaced a request of the "
            f"window's mean served size on {sus.avoided_counterfactual_model}."
        ),
    )


# ---------------------------------------------------------------------------
# GET /api/metrics/providers
# ---------------------------------------------------------------------------


def providers(tenant_id: str = "default", window_hours: int = 24) -> ProviderMetricsResponse:
    rows = _rows(tenant_id, window_hours)
    by: dict[str, dict] = {}

    def bucket(name: str) -> dict:
        return by.setdefault(name, {"requests": 0, "failures": 0, "in": 0, "out": 0, "lat": [], "last": None})

    for r in rows:
        if r.provider:
            b = bucket(r.provider)
            b["requests"] += 1
            if r.latency_provider_ms is not None:
                b["lat"].append(r.latency_provider_ms)
            if b["last"] is None or (r.timestamp and r.timestamp > b["last"]):
                b["last"] = r.timestamp
        if r.failover_used:
            if r.failover_from:
                fb = bucket(r.failover_from)
                fb["failures"] += 1
                fb["out"] += 1
            if r.failover_to:
                bucket(r.failover_to)["in"] += 1

    stats = [
        ProviderStat(
            provider=name,
            requests=b["requests"],
            failures=b["failures"],
            failover_in=b["in"],
            failover_out=b["out"],
            latency_p50_ms=percentile(b["lat"], 50),
            last_seen=b["last"].isoformat() if b["last"] else None,
        )
        for name, b in sorted(by.items())
    ]
    return ProviderMetricsResponse(
        window_hours=window_hours,
        providers=stats,
        failover_events=sum(1 for r in rows if r.failover_used),
    )


# ---------------------------------------------------------------------------
# GET /api/audit/report
# ---------------------------------------------------------------------------


def report(tenant_id: str = "default", since_hours: int = 168) -> AuditReport:
    """Sections mapped to the seven Trustworthy AI requirements.

    Each section is rows of evidence from the audit table, with a note that
    says what the numbers are and are not.
    """
    rows = _rows(tenant_id, since_hours)
    ov = overview(tenant_id, since_hours)
    sec = security(tenant_id, since_hours)
    sus = sustainability(tenant_id, since_hours)
    prov = providers(tenant_id, since_hours)

    from app.fairness import harness as fairness  # noqa: WPS433 - avoid import cycle

    fair = fairness.build_report()

    by_action = Counter(r.policy_action or "UNKNOWN" for r in rows)
    profiles = Counter(r.policy_profile or "unknown" for r in rows)
    versions = sorted({r.policy_version for r in rows if r.policy_version is not None})

    sections = [
        AuditReportSection(
            title="Automated decisions",
            requirement="EU HLEG 7 - Accountability",
            rows=[
                {"metric": "requests inspected", "value": ov.total_requests},
                *[{"metric": f"decision: {k}", "value": v} for k, v in sorted(by_action.items())],
                *[{"metric": f"policy profile: {k}", "value": v} for k, v in sorted(profiles.items())],
                {"metric": "policy versions in force", "value": versions},
                {"metric": "overrides applied after human review", "value": sum(1 for r in rows if r.override_applied)},
            ],
            note="Every row in request_audit records the decision, the policy version and the rules that fired.",
        ),
        AuditReportSection(
            title="Privacy and data governance",
            requirement="EU HLEG 3 - Privacy and data governance",
            rows=[
                {"metric": "personal data items detected", "value": sec.pii_detections},
                {"metric": "requests sanitised", "value": ov.sanitized_requests},
                {"metric": "credential-shaped values detected", "value": sec.secret_detections},
                {"metric": "credential leaks prevented", "value": sec.credential_blocks},
            ],
            note=(
                "Detection is heuristic. The audit table stores counts and types only; it has no column "
                "for prompt text, credentials or raw user identifiers."
            ),
        ),
        AuditReportSection(
            title="Robustness and safety",
            requirement="EU HLEG 2 - Technical robustness and safety",
            rows=[
                {"metric": "prompt-injection blocks", "value": sec.injection_blocks},
                {"metric": "provider failover events", "value": prov.failover_events},
                {"metric": "responses flagged on egress", "value": sec.egress_flags},
                {"metric": "top rules fired", "value": [f"{r.rule_id} x{r.count}" for r in sec.top_rules[:5]]},
            ],
            note="Injection defence covers known OWASP LLM01 patterns; it does not claim to catch novel attacks.",
        ),
        AuditReportSection(
            title="Human oversight",
            requirement="EU HLEG 1 - Human agency and oversight",
            rows=[
                {"metric": "appeals pending", "value": sec.reviews_pending},
                {"metric": "appeals approved", "value": sec.reviews_approved},
                {"metric": "appeals denied", "value": sec.reviews_denied},
            ],
            note="Every appealable block can be contested; approval mints a single-use, request-scoped override.",
        ),
        AuditReportSection(
            title="Fairness of detection",
            requirement="EU HLEG 5 - Diversity, non-discrimination and fairness",
            rows=(
                [
                    {"metric": f"PERSON recall: {g.group}", "value": g.recall}
                    for g in fair.current.groups
                ]
                + [
                    {"metric": "gap (best - worst)", "value": fair.current.recall_gap},
                    {"metric": "gap closed vs baseline", "value": fair.gap_closed},
                    {"metric": "measured at", "value": fair.current.run_at.isoformat()},
                ]
                if fair.current
                else [{"metric": "fairness run", "value": "none recorded -- POST /api/fairness/run"}]
            ),
            note=fair.disclaimer,
        ),
        AuditReportSection(
            title="Environmental impact",
            requirement="EU HLEG 6 - Societal and environmental well-being",
            rows=[
                {"metric": "cache hit rate", "value": sus.cache_hit_rate},
                {"metric": "estimated energy (Wh)", "value": sus.estimated_energy_wh},
                {"metric": "estimated CO2 (g)", "value": sus.estimated_co2_g},
                {"metric": "estimated energy avoided by cache (Wh)", "value": sus.estimated_energy_avoided_wh},
                {"metric": "estimated spend (USD)", "value": ov.cost.estimated_spend_usd},
                {"metric": "estimated saved (USD)", "value": ov.cost.estimated_saved_usd},
            ],
            note=sus.basis,
        ),
        AuditReportSection(
            title="Transparency",
            requirement="EU HLEG 4 - Transparency",
            rows=[
                {"metric": "inspector overhead p50 (ms)", "value": ov.latency.inspector_overhead_p50_ms},
                {"metric": "inspector overhead p95 (ms)", "value": ov.latency.inspector_overhead_p95_ms},
                {"metric": "end-to-end p50 (ms)", "value": ov.latency.p50_ms},
                {"metric": "end-to-end p95 (ms)", "value": ov.latency.p95_ms},
            ],
            note="Every stage duration is measured with a monotonic clock; none is estimated.",
        ),
    ]
    now = datetime.now(timezone.utc)
    return AuditReport(
        generated_at=now,
        window_start=now - timedelta(hours=since_hours),
        window_end=now,
        tenant_id=tenant_id,
        sections=sections,
        disclaimer=DISCLAIMER,
    )
