"""Stub responses for subsystems that have not shipped yet.

Phase 0 gave Person 2 a complete HTTP surface on day one by stubbing every
endpoint. Each phase since has replaced one stub with the real thing; this
module now holds only what remains:

    stub_egress            -> Phase 10 (grounding) and Phase 11 (harm/bias)
    stub_*_metrics         -> Phase 12 (aggregation over request_audit)
    stub_audit_*           -> Phase 8 / 12
    stub_reviews, _record  -> Phase 8 / 14

The ingress path -- /inspect -- is real as of Phase 7 (security/pipeline.py)
and nothing here is on it. /api/health reports per component which of the
above are still stubs.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.contracts.audit import (
    AuditEventPage,
    AuditEventRecord,
    AuditReport,
    AuditReportSection,
)
from app.contracts.common import (
    Decision,
    GroundingStatus,
    PipelineStage,
    ReviewStatus,
    StageStatus,
)
from app.contracts.egress import (
    BiasResult,
    EgressAction,
    EgressResponse,
    GroundingResult,
    SafetyResult,
)
from app.contracts.governance import (
    ReviewListResponse,
    ReviewRecord,
)
from app.contracts.metrics import (
    CostStats,
    LatencyStats,
    MetricsResponse,
    ProviderMetricsResponse,
    ProviderStat,
    RuleCount,
    SecurityMetricsResponse,
    SustainabilityMetricsResponse,
    TokenStats,
)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def stub_egress(request_id: str, response_text: str, has_reference: bool) -> EgressResponse:
    grounding = (
        GroundingResult(
            enabled=True,
            claims=10,
            supported=8,
            unsupported=2,
            contradicted=0,
            score=0.80,
            status=GroundingStatus.REVIEW,
            unsupported_claims=["The policy took effect in 2019."],
        )
        if has_reference
        else GroundingResult(enabled=False, status=GroundingStatus.SKIPPED)
    )
    pipeline = [
        PipelineStage(stage="harm_screen", status=StageStatus.SUCCESS, duration_ms=0.3),
        PipelineStage(stage="bias_screen", status=StageStatus.SUCCESS, duration_ms=0.3),
        PipelineStage(
            stage="grounding",
            status=StageStatus.WARNING if has_reference else StageStatus.SKIPPED,
            duration_ms=0.5 if has_reference else 0.0,
        ),
    ]
    return EgressResponse(
        request_id=request_id,
        safety=SafetyResult(),
        bias=BiasResult(),
        grounding=grounding,
        action=EgressAction.ANNOTATE if has_reference else EgressAction.PASS,
        replacement_text=None,
        explanation=(
            "2 of 10 claims could not be matched to the supplied document."
            if has_reference
            else "No harmful or biased content signals detected."
        ),
        pipeline=pipeline,
        total_duration_ms=sum(s.duration_ms for s in pipeline),
    )


COST_BASIS = "provider list price from config/pricing.yaml; stub values in Phase 0"
SUSTAINABILITY_BASIS = (
    "estimated from per-token energy assumptions in config/sustainability.yaml "
    "and a configurable grid intensity factor; stub values in Phase 0"
)


def stub_metrics(window_hours: int) -> MetricsResponse:
    return MetricsResponse(
        window_hours=window_hours,
        total_requests=0,
        blocked_requests=0,
        sanitized_requests=0,
        latency=LatencyStats(),
        tokens=TokenStats(),
        cost=CostStats(basis=COST_BASIS),
    )


def stub_security_metrics(window_hours: int) -> SecurityMetricsResponse:
    return SecurityMetricsResponse(window_hours=window_hours, top_rules=[RuleCount(rule_id="stub", count=0)])


def stub_sustainability_metrics(window_hours: int) -> SustainabilityMetricsResponse:
    return SustainabilityMetricsResponse(window_hours=window_hours, basis=SUSTAINABILITY_BASIS)


def stub_provider_metrics(window_hours: int) -> ProviderMetricsResponse:
    return ProviderMetricsResponse(
        window_hours=window_hours,
        providers=[ProviderStat(provider="stub", requests=0)],
        failover_events=0,
    )


def stub_audit_page(limit: int, offset: int) -> AuditEventPage:
    return AuditEventPage(items=[], total=0, limit=limit, offset=offset)


def stub_audit_report(tenant_id: str) -> AuditReport:
    return AuditReport(
        generated_at=_now(),
        tenant_id=tenant_id,
        sections=[
            AuditReportSection(
                title="Automated decisions",
                requirement="EU HLEG 7 - Accountability",
                rows=[],
                note="Populated from the request_audit table in Phase 12.",
            )
        ],
        disclaimer=(
            "This report is transaction evidence generated by Aegis. It supports "
            "a deployer's own record-keeping and oversight processes. It is not a "
            "conformity assessment and does not itself establish legal compliance."
        ),
    )


def stub_reviews() -> ReviewListResponse:
    return ReviewListResponse(items=[], total=0)


def stub_review_record(request_id: str, justification: str) -> ReviewRecord:
    return ReviewRecord(
        id="rev_stub000000",
        request_id=request_id,
        tenant_id="default",
        created_at=_now(),
        original_decision=Decision.BLOCK,
        rule_fired="injection.instruction_override",
        user_justification=justification,
        status=ReviewStatus.PENDING,
        reviewer_note=None,
        decided_at=None,
        override_expires_at=_now() + timedelta(minutes=15),
    )


__all__ = [
    "stub_audit_page",
    "stub_audit_report",
    "stub_egress",
    "stub_metrics",
    "stub_provider_metrics",
    "stub_review_record",
    "stub_reviews",
    "stub_security_metrics",
    "stub_sustainability_metrics",
]
