"""initial schema

Revision ID: 47c7b00f9031
Revises: 
Create Date: 2026-09-18 00:40:09.335613
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '47c7b00f9031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairness_eval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('detected', sa.Integer(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fairness_eval', schema=None) as batch_op:
        batch_op.create_index('ix_fairness_eval_run', ['run_id'], unique=False)

    op.create_table('policy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('yaml_body', sa.Text(), nullable=False),
    sa.Column('author_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_policy_version_version')
    )
    op.create_table('request_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('routed_complexity', sa.String(length=16), nullable=True),
    sa.Column('latency_total_ms', sa.Float(), nullable=True),
    sa.Column('latency_inspect_ms', sa.Float(), nullable=True),
    sa.Column('latency_provider_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('cache_similarity', sa.Float(), nullable=True),
    sa.Column('pii_detected', sa.Boolean(), nullable=False),
    sa.Column('pii_count', sa.Integer(), nullable=False),
    sa.Column('pii_types', sa.JSON(), nullable=False),
    sa.Column('secret_detected', sa.Boolean(), nullable=False),
    sa.Column('secret_count', sa.Integer(), nullable=False),
    sa.Column('secret_types', sa.JSON(), nullable=False),
    sa.Column('injection_detected', sa.Boolean(), nullable=False),
    sa.Column('injection_score', sa.Float(), nullable=True),
    sa.Column('entropy_count', sa.Integer(), nullable=False),
    sa.Column('policy_action', sa.String(length=16), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('policy_profile', sa.String(length=64), nullable=True),
    sa.Column('rules_fired', sa.JSON(), nullable=False),
    sa.Column('block_code', sa.String(length=64), nullable=True),
    sa.Column('override_applied', sa.Boolean(), nullable=False),
    sa.Column('failover_used', sa.Boolean(), nullable=False),
    sa.Column('failover_from', sa.String(length=64), nullable=True),
    sa.Column('failover_to', sa.String(length=64), nullable=True),
    sa.Column('egress_flagged', sa.Boolean(), nullable=False),
    sa.Column('egress_categories', sa.JSON(), nullable=False),
    sa.Column('grounding_enabled', sa.Boolean(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=True),
    sa.Column('grounding_status', sa.String(length=16), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('estimated_savings_usd', sa.Float(), nullable=True),
    sa.Column('estimated_energy_wh', sa.Float(), nullable=True),
    sa.Column('estimated_co2_g', sa.Float(), nullable=True),
    sa.Column('review_id', sa.String(length=64), nullable=True),
    sa.Column('stage_timings_ms', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('gateway_finalized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_request_audit_request_id')
    )
    with op.batch_alter_table('request_audit', schema=None) as batch_op:
        batch_op.create_index('ix_request_audit_tenant_ts', ['tenant_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_request_audit_user_hash', ['user_ref_hash'], unique=False)

    op.create_table('review_request',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requester_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('original_decision', sa.String(length=16), nullable=False),
    sa.Column('rule_fired', sa.String(length=128), nullable=True),
    sa.Column('user_justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_token_hash', sa.String(length=64), nullable=True),
    sa.Column('override_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_request', schema=None) as batch_op:
        batch_op.create_index('ix_review_request_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_review_request_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_request', schema=None) as batch_op:
        batch_op.drop_index('ix_review_request_status')
        batch_op.drop_index('ix_review_request_request_id')

    op.drop_table('review_request')
    with op.batch_alter_table('request_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_request_audit_user_hash')
        batch_op.drop_index('ix_request_audit_tenant_ts')

    op.drop_table('request_audit')
    op.drop_table('policy_version')
    with op.batch_alter_table('fairness_eval', schema=None) as batch_op:
        batch_op.drop_index('ix_fairness_eval_run')

    op.drop_table('fairness_eval')
    # ### end Alembic commands ###
